version: "3.9"
services:
  crawler:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    environment:
      - DB_USER=klaas
      - DB_PASS=password
      - DB_NAME=crawling
      - DB_HOST=db
    links:
      - "db"

  db:
    image: "postgres:13.1-alpine"
    environment:
      - POSTGRES_USER=klaas
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crawling
    ports:
      - "5432:5432"
    volumes:
      - chefkoch_data:/var/lib/postgresql/data
      - ./var/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  chefkoch_data:
